export const cards =[
    { imageSrc: 'https://i.imgur.com/QpmXELP.png', title: 'The Importance of Diversity in Space Exploration', description: 'Valuing diverse perspectives, backgrounds, talents, and experiences amplifies our comprehension of the universe and nurtures a just and equitable future for everyone, making space exploration more successful and inclusive.', slug: 'card-grid-layout-1' },
    { imageSrc: 'https://i.imgur.com/HVoh2n4.png', title: 'Here\'s How to Register for SpaceApps 2023!', description: 'Register for NASA\'s SpaceApps Challenge 2023 at TU Shannon, Ireland. Explore the website, find the local event (HackAthlone), choose individual or team registration, access resources, and prepare for an exciting cosmic adventure in space exploration.', slug: '2' },
    { imageSrc: 'https://i.imgur.com/YqPwz7l.png', title: 'Navigating the SpaceApps Hackathon Challenges', description: 'Explore NASA\'s SpaceApps Challenge 2023 with 31 unique challenges across four domains: Space Exploration, Creative, Data Science, and Game Development. Tailor your cosmic journey by selecting challenges based on difficulty and your passion.', slug: '3' },
    { imageSrc: 'https://i.imgur.com/pk4xjMf.png', title: 'Seven Reasons to Choose Space Apps Athlone', description: 'Space Apps Athlone promises NASA\'s Open Data, expert networking, 48-hour innovation in top-notch facilities, a hardware toolkit, sustained meals, and exciting prizes, including a NASA trip—an opportunity to elevate your career. Join the space exploration!', slug: '4' },
    { imageSrc: 'https://i.imgur.com/NqvBau2.jpeg', title: 'Hacking the Night Away: Unveiling the Thrills of SpaceApps Athlone 2024', description: 'Are you ready to embark on a journey of innovation, sleepless nights, and boundless camaraderie? Look no further than SpaceApps Athlone 2024, a hackathon experience that will leave you exhilarated and inspired. Picture a weekend filled with coding, problem-solving, and networking with like-minded individuals from around the globe, all set against the backdrop of NASA’s International Space Apps Challenge.', slug: '5' },
    { imageSrc: 'https://i.imgur.com/K803F8Z.jpeg', title: 'Decoding the SpaceApps Challenge 2023: How Projects Soar to Victory', description: 'As you gear up for the exhilarating journey of SpaceApps Athlone 2024, you might be curious about how your project will be judged and what criteria will guide the selection of the winners. We’ve established a transparent and comprehensive judging process to ensure that every participant understands what it takes to achieve stellar success.', slug: '6' },
    { imageSrc: 'https://i.imgur.com/GHqELEK.jpeg', title: 'Understanding the Judging Process', description: 'Before diving into the specific criteria, let’s clarify the overall judging process. At SpaceApps Athlone, fairness and equity are at the core of how we recognize the brilliance of each project. Here’s a breakdown of how the judging unfolds:', slug: '7' },
    { imageSrc: 'https://i.imgur.com/fO5GbMO.jpeg', title: 'Navigating Your Way to NASA SpaceApps Challenge at TU Shannon in Athlone', description: 'To help you get there, we’ve put together a handy guide on how to reach TU Shannon’s engineering building from major cities like Dublin, Limerick, Cork, and Galway.', slug: '8' },
    { imageSrc: 'https://i.imgur.com/PPjAUbl.jpeg', title: 'How Hackathons Fuel Personal Growth and Prepare You for Life\'s Challenges', description: 'Hackathons are not just about coding and competition; they are transformative experiences that mold individuals into resilient, innovative thinkers ready to tackle real-world challenges. Whether you\'re a seasoned developer or a newcomer to the tech scene, participating in a hackathon like SpaceApps Athlone can significantly impact your personal growth and readiness for future endeavors.', slug: '9' },
    { imageSrc: 'https://i.imgur.com/FLcz4Qn.jpeg', title: 'Mastering SpaceApps Athlone: Tips for a Stellar Hackathon Experience', description: 'Hackathons are not just about coding and competition; they are transformative experiences that mold individuals into resilient, innovative thinkers ready to tackle real-world challenges. Whether you\'re a seasoned developer or a newcomer to the tech scene, participating in a hackathon like SpaceApps Athlone can significantly impact your personal growth and readiness for future endeavors.', slug: '10' },
  
];